name: EMPRESS Sync

# on:
#   schedule:
#     - cron: '*/15 * * * *'
on:
  workflow_dispatch:

jobs:
  mutate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Sync Logs to S3
        run: aws s3 cp mutation.log s3://empress-throne/logs/mutation.log
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
